// <auto-generated />
using Library.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260119141614_initial2")]
    partial class initial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Library.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "F. Scott Fitzgerald",
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Ernest Hemingway",
                            Title = "The Sun Also Rises"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "John Steinbeck",
                            Title = "East of Eden"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Edith Wharton",
                            Title = "The House of Mirth"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "John Grisham",
                            Title = "A Time to Kill"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Evelyn Waugh",
                            Title = "Vile Bodies"
                        },
                        new
                        {
                            BookId = 7,
                            Author = "Philip K. Dick",
                            Title = "A Scanner Darkly"
                        },
                        new
                        {
                            BookId = 8,
                            Author = "Stephen Fry",
                            Title = "Moab is my Washpot"
                        },
                        new
                        {
                            BookId = 9,
                            Author = "Lois Lowry",
                            Title = "Number the Stars"
                        },
                        new
                        {
                            BookId = 10,
                            Author = "Aldous Huxley",
                            Title = "Brave New World"
                        });
                });

            modelBuilder.Entity("Library.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "s.ayasa@gmail.com",
                            FullName = "shahd",
                            Password = "123"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "s.barham@gmail.com",
                            FullName = "Sanabel",
                            Password = "456"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "r.kmail@gmail.com",
                            FullName = "ranin",
                            Password = "789"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "r.ali@gmail.com",
                            FullName = "randa",
                            Password = "432"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "m.aref@gmail.com",
                            FullName = "malak",
                            Password = "564"
                        },
                        new
                        {
                            UserId = 6,
                            Email = "r.ayasa@gmail.com",
                            FullName = "raghad",
                            Password = "577"
                        },
                        new
                        {
                            UserId = 7,
                            Email = "b.ayasa@gmail.com",
                            FullName = "baylasan",
                            Password = "363"
                        },
                        new
                        {
                            UserId = 8,
                            Email = "l.mashaqi@gmail.com",
                            FullName = "leen",
                            Password = "130"
                        },
                        new
                        {
                            UserId = 9,
                            Email = "s.shehab@gmail.com",
                            FullName = "shahed",
                            Password = "325"
                        },
                        new
                        {
                            UserId = 10,
                            Email = "a.atiya@gmail.com",
                            FullName = "aseel",
                            Password = "333"
                        });
                });

            modelBuilder.Entity("Library.Models.Book", b =>
                {
                    b.HasOne("Library.Models.User", "User")
                        .WithMany("Books")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Library.Models.User", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
